"""add completed_by to chore

Revision ID: 5fedc611c286
Revises: 2bd3ece89df0
Create Date: 2026-03-25 23:36:43.488181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fedc611c286'
down_revision = '2bd3ece89df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_chore_completed_by', 'user', ['completed_by'], ['id'])

    with op.batch_alter_table('reward_redemption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='approved', nullable=True))

    op.create_table('site_banner',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('title', sa.String(length=100), nullable=False, server_default='Site Notice'),
        sa.Column('message', sa.String(length=500), nullable=False, server_default=''),
        sa.Column('banner_type', sa.String(length=20), nullable=False, server_default='info'),
        sa.Column('is_active', sa.Boolean(), server_default='0'),
        sa.Column('show_on_index', sa.Boolean(), server_default='1'),
        sa.Column('show_on_all_pages', sa.Boolean(), server_default='0'),
        sa.Column('created_at', sa.DateTime()),
        sa.Column('updated_by', sa.Integer(), sa.ForeignKey('user.id'), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_banner')

    with op.batch_alter_table('reward_redemption', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chore_completed_by', type_='foreignkey')
        batch_op.drop_column('completed_by')

    # ### end Alembic commands ###
