"""add completed_by to chore

Revision ID: 5fedc611c286
Revises: 2bd3ece89df0
Create Date: 2026-03-25 23:36:43.488181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fedc611c286'
down_revision = '2bd3ece89df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['completed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('completed_by')

    # ### end Alembic commands ###
